//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int AddrID { get; set; }
        public string AddrLine1 { get; set; }
        public string AddrLine2 { get; set; }
        public string AddrLine3 { get; set; }
        public string AddrLine4 { get; set; }
        public string AddrLine5 { get; set; }
        public string AddrCity { get; set; }
        public string AddrState { get; set; }
        public string AddrPostalCode { get; set; }
        public string AddrCountry { get; set; }
        public string AddrNote { get; set; }
    }
}
