//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency
    {
        public string CurrencyID { get; set; }
        public string CurrencyName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyFormat_ThousandSeparator { get; set; }
        public string CurrencyFormat_ThousandSeparatorGrouping { get; set; }
        public string CurrencyFormat_DecimalPlaces { get; set; }
        public string CurrencyFormat_DecimalSeparator { get; set; }
        public Nullable<bool> IsUserDefinedCurrency { get; set; }
        public Nullable<double> ExchangeRate { get; set; }
        public Nullable<System.DateTime> AsOfDate { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
