//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string ID { get; set; }
        public string PSID { get; set; }
        public string AmazID { get; set; }
        public string EbayID { get; set; }
        public string IzetlID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string AccountNumber { get; set; }
        public string Company { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> CustomerBalance { get; set; }
        public string Contact { get; set; }
        public string Type { get; set; }
        public string TypeId { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string AlternateContact { get; set; }
        public string AlternatePhone { get; set; }
        public string Email { get; set; }
        public string Cc { get; set; }
        public string AdditionalContactInfo { get; set; }
        public string ClassName { get; set; }
        public string ClassId { get; set; }
        public string Notes { get; set; }
        public string ParentName { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Sublevel { get; set; }
        public string JobStatus { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public Nullable<System.DateTime> JobProjectedEndDate { get; set; }
        public Nullable<System.DateTime> JobEndDate { get; set; }
        public string JobDescription { get; set; }
        public string JobType { get; set; }
        public string JobTypeId { get; set; }
        public string CreditCardAddress { get; set; }
        public Nullable<int> CreditCardExpMonth { get; set; }
        public Nullable<int> CreditCardExpYear { get; set; }
        public string CreditCardNameOnCard { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardPostalCode { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public string BillingAddress { get; set; }
        public string BillingLine1 { get; set; }
        public string BillingLine2 { get; set; }
        public string BillingLine3 { get; set; }
        public string BillingLine4 { get; set; }
        public string BillingLine5 { get; set; }
        public string BillingCity { get; set; }
        public string BillingState { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingCountry { get; set; }
        public string BillingNote { get; set; }
        public string ShippingAddress { get; set; }
        public string ShippingLine1 { get; set; }
        public string ShippingLine2 { get; set; }
        public string ShippingLine3 { get; set; }
        public string ShippingLine4 { get; set; }
        public string ShippingLine5 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingPostalCode { get; set; }
        public string ShippingCountry { get; set; }
        public string ShippingNote { get; set; }
        public string ResaleNumber { get; set; }
        public string SalesRep { get; set; }
        public string SalesRepId { get; set; }
        public string Terms { get; set; }
        public string TermsId { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyId { get; set; }
        public string TaxCode { get; set; }
        public string TaxCodeId { get; set; }
        public string TaxItem { get; set; }
        public string TaxItemId { get; set; }
        public string SalesTaxCountry { get; set; }
        public string PriceLevel { get; set; }
        public string PriceLevelId { get; set; }
        public string PreferredDeliveryMethod { get; set; }
        public string PreferredPaymentMethodName { get; set; }
        public string PreferredPaymentMethodId { get; set; }
        public string PrintAs { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CustomFields { get; set; }
        public string EditSequence { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public string Barcode { get; set; }
    
        public virtual customertype customertype { get; set; }
    }
}
