//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickBooksToLocalV2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class synncquickbooksEntities : DbContext
    {
        public synncquickbooksEntities()
            : base("name=synncquickbooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<addresstype> addresstypes { get; set; }
        public virtual DbSet<currency> currencies { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<customertype> customertypes { get; set; }
        public virtual DbSet<invoicelineitem> invoicelineitems { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<salesrep> salesreps { get; set; }
        public virtual DbSet<salestaxcode> salestaxcodes { get; set; }
        public virtual DbSet<salestaxitem> salestaxitems { get; set; }
    }
}
